# Get users list
user_list:
    path: /users/
    controller: \App\Controller\Rest\UsersController::getUsersList
    methods: [GET, HEAD]

add_user:
    path: /users/
    controller: \App\Controller\Rest\UsersController